/* oxlint-disable next/no-html-link-for-pages, next/no-img-element, jsx-a11y/media-has-caption -- Static Pages uses document navigation and original renders. The CFD videos are silent; adjacent text describes both sequences and their limitations. */
import { categories, featuredProjects, projects, projectUrl } from '@/lib/projects';
import { GridlineShell } from '@/components/gridline-shell';

const flowBase = '/dell-5560-wall-mount/simulation/revh-transient/sequence/';
const renders = [
  { slug: '5680-dock', name: 'Precision 5680 / D8', src: '/5680-dock/assets/D8-assembled.png', alt: 'CAD assembly of the Precision 5680 dock with laptop, recessed fans and adjustable connector', caption: 'ASSEMBLY RENDER · D8 PROTOTYPE' },
  { slug: 'dell-5560-wall-mount', name: 'Laptop wall mount / M1.1', src: '/dell-5560-wall-mount/assets/minimalist-with-envelopes.png', alt: 'Minimalist laptop wall mount CAD with laptop and fan envelopes', caption: 'CAD GEOMETRY · M1.1 PROTOTYPE' },
  { slug: 'peg', name: 'Conformal pegboard anchor', src: 'https://raw.githubusercontent.com/thereprocase/peg/main/visuals/conformal-hero.png', alt: 'Rendered conformal pegboard anchor and curved bearing surfaces', caption: 'GEOMETRY STUDY · PROTOTYPE' },
];

export default function Home() {
  return <GridlineShell>
    <section className="gl-introduction"><div><p className="gl-kicker">TOOLS / HARDWARE / EXPERIMENTS</p><h1>The project directory.</h1><p>Browse the work, inspect the models, and follow the evidence.</p></div><dl className="gl-counts"><div><dt>Featured</dt><dd>{featuredProjects.length.toString().padStart(2, '0')}</dd></div><div><dt>Groups</dt><dd>{categories.length.toString().padStart(2, '0')}</dd></div><div><dt>Sites</dt><dd>{(featuredProjects.length + 1).toString().padStart(2, '0')}</dd></div></dl></section>
    <section className="gl-pane" aria-labelledby="featured-title"><div className="gl-pane-title"><h2 id="featured-title">FEATURED / AGENT COLLABORATION</h2><span>02 PROJECTS</span></div><div className="gl-featured">{projects.filter(project => project.spotlight).map(project => <article key={project.slug}><p className="gl-kicker">{project.slug === 'trio' ? 'COORDINATE THE WORK' : 'REVIEW THE RESULT'}</p><h3><a href={projectUrl(project)}>{project.name} <span aria-hidden="true">↗</span></a></h3><p>{project.summary}</p><p className="gl-use-case">{project.slug === 'trio' ? 'Use it when independent coding sessions need to share tasks and coordinate their work.' : 'Use it when a change needs several review perspectives and a documented path through the fixes.'}</p><div className="gl-project-actions"><a className="gl-button" href={projectUrl(project)}>Explore project →</a><a className="gl-button" href={project.links[1].href}>{project.slug === 'trio' ? 'Setup & documentation ↗' : 'Install & workflows ↗'}</a></div></article>)}</div></section>
    <section className="gl-pane" id="render-library" aria-labelledby="renders-title"><div className="gl-pane-title"><h2 id="renders-title">RENDER LIBRARY / HARDWARE &amp; MECHANISMS</h2><span>03 STUDIES</span></div><div className="gl-render-grid">{renders.map(render => <figure key={render.slug}><a className="gl-render-link" href={`/${render.slug}/`}><img src={render.src} alt={render.alt} width="1000" height="750" loading="lazy" /></a><figcaption><span className="gl-state">{render.caption}</span><a href={`/${render.slug}/`}>{render.name} ↗</a></figcaption></figure>)}</div><p className="gl-caution">PROTOTYPES / Rendered geometry. Physical fit, loads, and cooling still require testing.</p></section>
    <section className="gl-pane gl-flow-pane" id="airflow" aria-labelledby="airflow-title"><div className="gl-pane-title gl-linked"><h2 id="airflow-title">REV H / FINAL FLOW VIDEOS</h2><span>60 FPS / SIMULATION PAUSED</span></div><div className="gl-flow-grid">{[{ name: 'Startup from still air', path: '', id: 'A' }, { name: 'Already flowing', path: 'flowing/', id: 'B' }].map(item => <figure key={item.id}><div className="gl-media-label"><span>SEQUENCE {item.id}</span><h3>{item.name}</h3><span>ABOUT 1/200TH SPEED</span></div><video controls playsInline preload="none" poster={flowBase + item.path + 'latest-tracers.png'}><source src={flowBase + item.path + 'latest-tracers.mp4'} type="video/mp4" /><a href={flowBase + item.path + 'latest-tracers.mp4'}>Open the particle-flow MP4</a></video><figcaption><a href={flowBase + item.path + 'latest-tracers.mp4'}>Open MP4 ↗</a><a href={flowBase + item.path}>Checkpoint record →</a></figcaption></figure>)}</div><p className="gl-caution">EXPLORATORY CFD / Particles follow recorded velocity fields. The flowing case begins from an unconverged field; mesh and timestep independence remain untested.</p></section>
    <div id="projects">{categories.map((category, index) => <section className="gl-pane gl-register" id={category.id} aria-labelledby={`${category.id}-title`} key={category.id}><div className="gl-pane-title"><h2 id={`${category.id}-title`}>0{index + 1} / {category.name.toUpperCase()}</h2><span>{projects.filter(project => project.category === category.id).length.toString().padStart(2, '0')} PROJECTS</span></div><p className="gl-register-description">{category.description}</p><div className="gl-register-head" aria-hidden="true"><span>PROJECT</span><span>PURPOSE</span><span>OPEN</span></div>{projects.filter(project => project.category === category.id).map(project => <a className="gl-project-row" href={projectUrl(project)} key={project.slug}><strong>{project.name}</strong><span>{project.summary}</span><span className="gl-row-action" aria-hidden="true">Open &rarr;</span></a>)}</section>)}</div>
  </GridlineShell>;
}
