/* oxlint-disable next/no-html-link-for-pages, next/no-img-element -- Static Pages uses document navigation and original renders. */
import { categories, featuredProjects, projects, projectUrl } from '@/lib/projects';
import { GridlineShell } from '@/components/gridline-shell';

const renders = [
  { slug: 'spool-wall-rack', name: 'Spool wall rack / E13', src: '/spool-wall-rack/assets/finish-inner-front.png', alt: 'Close-up of the E13 inner rod seat showing the retained flexible fingers and chamfer finish', caption: 'INNER SEAT · E13 PROTOTYPE' },
  { slug: 'p1s-feet', name: 'P1S squash-ball cradle / P02', src: '/p1s-feet/p02/print-layout.png', alt: 'CAD render of the gray base and teal cradle side by side in their flat printing orientations', caption: 'PRINT LAYOUT · P02 PROTOTYPE' },
  { slug: 'peg', name: 'Conformal pegboard anchor', src: 'https://raw.githubusercontent.com/thereprocase/peg/main/visuals/conformal-hero.png', alt: 'Rendered conformal pegboard anchor and curved bearing surfaces', caption: 'GEOMETRY STUDY · PROTOTYPE' },
];

export default function Home() {
  return <GridlineShell>
    <section className="gl-introduction"><div><p className="gl-kicker">TOOLS / HARDWARE / EXPERIMENTS</p><h1>The project directory.</h1><p>Printable hardware, a typeface for FDM printing, and software tools, with source files and downloads.</p></div><dl className="gl-counts"><div><dt>Projects</dt><dd>{featuredProjects.length.toString().padStart(2, '0')}</dd></div><div><dt>Groups</dt><dd>{categories.length.toString().padStart(2, '0')}</dd></div><div><dt>Sites</dt><dd>{(featuredProjects.length + 1).toString().padStart(2, '0')}</dd></div></dl></section>
    <section className="gl-pane sr-home-feature" aria-labelledby="font-feature-title"><div className="gl-pane-title"><h2 id="font-feature-title">NEW TYPEFACE / FILLAPRINT</h2><span>THREE FAMILIES · FREE TO USE</span></div><div className="sr-hero-grid"><div className="sr-hero-copy"><p className="gl-kicker">FOR FDM 3D PRINTING</p><h3>Equal minimum widths for strokes and gaps.</h3><p>Nominal strokes and minimum clear gaps are both two extrusion widths.</p><div className="sr-actions"><a className="gl-button" href="/fillaprint/">Font specimens →</a><a className="gl-button" href="/fillaprint/#downloads">Download the fonts ↓</a></div><p className="sr-caption">SIL Open Font License 1.1 · personal and commercial use.</p></div><a className="sr-home-image" href="/fillaprint/" aria-label="Fillaprint specimens"><img src="/fillaprint/images/hero.png" alt="Fillaprint font specimen with measurement symbols" width="1600" height="900" /></a></div></section>
    <section className="gl-pane sr-home-feature" aria-labelledby="feet-feature-title"><div className="gl-pane-title"><h2 id="feet-feature-title">FEATURED HARDWARE / TPU ISOLATION FEET</h2><span>C01 PAVER · P02 PRINTER</span></div><div className="sr-hero-grid"><div className="sr-hero-copy"><p className="gl-kicker">PRINTER → PAVER → SHELF</p><h3>Two-piece TPU feet for a P1S and a concrete paver.</h3><p>Explore the two-piece TPU feet: flat 3-inch square supports under a concrete paver, and squash-ball cradles under the P1S. Rotate the actual models, check load and clearance assumptions, and download printable CAD.</p><div className="sr-actions"><a className="gl-button" href="/paver-feet/">Explore paver feet →</a><a className="gl-button" href="/p1s-feet/">Explore P1S ball cradles →</a><a className="gl-button" href="/paver-feet/#files">Paver STL &amp; STEP ↓</a></div><p className="sr-caption">Actual C01 CAD, exploded to show the floating pad and base. Engineering prototypes; attenuation and long-term loading need physical testing.</p></div><a className="sr-home-image" href="/paver-feet/" aria-label="Explore the TPU paver feet"><img src="/paver-feet/featured.png" alt="Exploded CAD render of a teal floating TPU pad above its square gray base" width="1500" height="1050" /></a></div></section>
    <section className="gl-pane" id="render-library" aria-labelledby="renders-title"><div className="gl-pane-title"><h2 id="renders-title">RENDER LIBRARY / HARDWARE &amp; MECHANISMS</h2><span>{renders.length.toString().padStart(2, '0')} STUDIES</span></div><div className="gl-render-grid">{renders.map(render => <figure key={render.slug}><a className="gl-render-link" href={`/${render.slug}/`}><img src={render.src} alt={render.alt} width="1000" height="750" loading="lazy" /></a><figcaption><span className="gl-state">{render.caption}</span><a href={`/${render.slug}/`}>{render.name} ↗</a></figcaption></figure>)}</div><p className="gl-caution">PROTOTYPES / Rendered geometry. Physical fit and loads still require testing.</p></section>
    <section className="gl-pane sr-home-feature" aria-labelledby="rack-feature-title"><div className="gl-pane-title"><h2 id="rack-feature-title">FEATURED HARDWARE / SPOOL WALL RACK</h2><span>E13 · ANGULAR REINFORCEMENT</span></div><div className="sr-hero-grid"><div className="sr-hero-copy"><p className="gl-kicker">FDM-PRINTED WALL BRACKET</p><h3>A printed two-rail spool rack.</h3><p>A compact printed bracket with two rod seats, retained snap fingers and straight underside tapers. Explore the shape, inspect the refined stress fields, and download the aligned print geometry.</p><div className="sr-actions"><a className="gl-button" href="/spool-wall-rack/">Explore the spool wall rack →</a><a className="gl-button" href="/spool-wall-rack/#downloads">CAD &amp; print setup ↓</a></div><p className="sr-caption">E13 engineering prototype · physical qualification remains.</p></div><a className="sr-home-image" href="/spool-wall-rack/" aria-label="Explore the E13 spool wall rack"><img src="/spool-wall-rack/assets/progress-exterior.png" alt="E13 spool rack bracket with two rod seats and angular reinforcement" width="1728" height="1440" loading="lazy" /></a></div></section>
    <div id="projects">{categories.map((category, index) => <section className="gl-pane gl-register" id={category.id} aria-labelledby={`${category.id}-title`} key={category.id}><div className="gl-pane-title"><h2 id={`${category.id}-title`}>0{index + 1} / {category.name.toUpperCase()}</h2><span>{projects.filter(project => project.category === category.id).length.toString().padStart(2, '0')} {projects.filter(project => project.category === category.id).length === 1 ? 'PROJECT' : 'PROJECTS'}</span></div><p className="gl-register-description">{category.description}</p><div className="gl-register-head" aria-hidden="true"><span>PROJECT</span><span>PURPOSE</span><span>OPEN</span></div>{projects.filter(project => project.category === category.id).map(project => <a className="gl-project-row" href={projectUrl(project)} key={project.slug}><strong>{project.name}</strong><span>{project.summary}</span><span className="gl-row-action" aria-hidden="true">Open &rarr;</span></a>)}</section>)}</div>
  </GridlineShell>;
}
